from __future__ import annotations

import importlib.util
import os
import unittest
from pathlib import Path
from unittest import mock

ROOT = Path(__file__).resolve().parents[2]


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader
    spec.loader.exec_module(module)
    return module


SITE = load_module("build_vision_audit_site", ROOT / "scripts/build_vision_audit_site.py")
SLACK = load_module("notify_vision_slack", ROOT / ".github/scripts/notify_vision_slack.py")
PIPELINE_SLACK = load_module("notify_slack", ROOT / ".github/scripts/notify_slack.py")
LLM_SITE = load_module("build_llm_judge_site", ROOT / "scripts/build_llm_judge_site.py")


def sample_report() -> dict:
    return {
        "status": "passed",
        "model": "qwen3-vl-30b-a3b-screen:latest",
        "model_provenance": {
            "execution": "local-only",
            "provider": "Ollama",
            "endpoint": "http://127.0.0.1:11434",
            "cloud_llm_calls": 0,
        },
        "model_usage": {"calls": 1, "prompt_tokens": 100, "completion_tokens": 20},
        "steps": [{
            "step": 1,
            "test_case_id": "VISION-001",
            "test_case_name": "AI Chat returns a real answer",
            "test_case_type": "dynamic exploratory check generated by the local Vision model",
            "objective": "Verify initial render.",
            "expected_result": "No concrete defect.",
            "actual_result": "No calibrated defects confirmed.",
            "scenario_input": "What does a smoke test verify?",
            "scenario_output": "It verifies that critical functionality is available.",
            "deterministic_passed": True,
            "verdict": "passed",
            "url": "https://www.alexpavsky.com/",
            "title": "Alex Pavlovsky",
            "screenshot": "/runner/vision-audit/screenshots/step-01.png",
            "summary": "The page rendered correctly.",
            "decision": {
                "next_action_executed": {
                    "kind": "scroll",
                    "direction": "down",
                    "reason": "Expand coverage.",
                },
            },
            "action_result": {"executed": True, "action": "scroll:down"},
            "model_latency_ms": 1234,
            "browser_evidence": {},
            "candidate_findings": [],
            "confirmed_findings": [],
        }],
        "confirmed_findings": [],
    }


class VisionAuditReportingTests(unittest.TestCase):
    def test_agent_has_ten_required_openings_and_live_ai_journeys(self):
        source = (ROOT / ".github/scripts/vision_audit_agent.mjs").read_text(encoding="utf-8")
        for index in range(1, 11):
            self.assertIn(f"LINK-{index:03d}", source)
        for case_id in ("CHAT-001", "CHAT-002", "VOICE-001", "VOICE-002", "CHALLENGE-001"):
            self.assertIn(case_id, source)

    def test_bosgame_workflow_avoids_broken_marketplace_action_extraction(self):
        workflow = (ROOT / ".github/workflows/agentic-vision-audit.yml").read_text(encoding="utf-8")
        self.assertNotIn("uses:", workflow)
        self.assertIn("http://127.0.0.1:11435", workflow)
        self.assertIn("daily-audit-runs/${{ github.run_id }}", workflow)
        self.assertIn("Daily Audit report is stale", workflow)
        self.assertIn("Post summary and every test case to Slack", workflow)

    def test_ragas_completion_requires_current_run_reports_and_eval_steps(self):
        workflow = (ROOT / ".github/workflows/ragas-nightly.yml").read_text(encoding="utf-8")
        self.assertIn("ragas-giskard-start-ns", workflow)
        self.assertIn("Stale report from an earlier run", workflow)
        self.assertIn("RAGAS_EVAL: ${{ steps.ragas_eval.outcome }}", workflow)
        self.assertIn("GISKARD_EVAL: ${{ steps.giskard_eval.outcome }}", workflow)
        self.assertIn("GISKARD_SCAN: ${{ steps.giskard_scan.outcome }}", workflow)

    def test_slack_delivery_cannot_pass_without_a_token(self):
        argv = ["notify_slack.py", "--channel", "C123", "--pipeline", "unit", "--require-delivery"]
        with mock.patch.dict(os.environ, {}, clear=True), mock.patch("sys.argv", argv):
            with self.assertRaises(SystemExit) as raised:
                PIPELINE_SLACK.main()
        self.assertEqual(raised.exception.code, 1)

    def test_llm_judge_site_keeps_only_latest_retry_per_test(self):
        records = [
            {"testFile": "a.spec.ts", "titlePath": ["suite", "case"], "retry": 0, "prompt": "old"},
            {"testFile": "a.spec.ts", "titlePath": ["suite", "case"], "retry": 1, "prompt": "new-1"},
            {"testFile": "a.spec.ts", "titlePath": ["suite", "case"], "retry": 1, "prompt": "new-2"},
            {"testFile": "b.spec.ts", "titlePath": ["case"], "retry": 0, "prompt": "other"},
        ]
        tests = [
            {"path": ["suite"], "title": "case", "retry": 1},
            {"path": [], "title": "case", "retry": 0},
        ]
        filtered = LLM_SITE.final_attempt_verdicts(records, tests)
        self.assertEqual([record["prompt"] for record in filtered], ["new-1", "new-2", "other"])

    def test_html_documents_evidence_and_local_model_provenance(self):
        html = SITE.run_html(sample_report())
        self.assertIn("VISION-001", html)
        self.assertIn("Verify initial render.", html)
        self.assertIn("No concrete defect.", html)
        self.assertIn("The page rendered correctly.", html)
        self.assertIn("What does a smoke test verify?", html)
        self.assertIn("It verifies that critical functionality is available.", html)
        self.assertIn("screenshots/step-01.png", html)
        self.assertIn("http://127.0.0.1:11434", html)
        self.assertIn("cloud evaluator calls: <strong>0</strong>", html)
        self.assertIn("production systems under test", html)

    def test_slack_thread_has_case_details_and_public_screenshot(self):
        step = sample_report()["steps"][0]
        blocks = SLACK.test_case_blocks(
            step,
            "https://qa-apps.github.io/PW_alexpavsky/vision-audit/runs/510/",
        )
        rendered = str(blocks)
        self.assertIn("VISION-001", rendered)
        self.assertIn("Verify initial render.", rendered)
        self.assertIn("Expected", rendered)
        self.assertIn("Local Vision analysis", rendered)
        self.assertIn("What does a smoke test verify?", rendered)
        self.assertIn("It verifies that critical functionality is available.", rendered)
        self.assertIn("scroll:down", rendered)
        self.assertIn("runs/510/screenshots/step-01.png", rendered)


if __name__ == "__main__":
    unittest.main()
